### ISSUE TITLE
is this the id of the file?

### ISSUE THREAD

**Issue by Khang5687** [EtiTheSpirit/BNKReplacer#3]
having problem with no man's audio suite so i used ww2ogg and got this output. Can I ask this is the id of my wem file?
![image](https://user-images.githubusercontent.com/22163416/108633710-440d9280-74a8-11eb-83d2-8e61da3a1999.png)

**Comment by EtiTheSpirit** [comment]
No, that's the amount of samples. See [this](https://www.izotope.com/en/learn/digital-audio-basics-sample-rate-and-bit-depth.html#:~:text=The%20sound%20wave%20is%20converted,thousands%20of%20measurements%20per%20second.) for more info on what a sample is, if you are curious enough. I think this highlighted link will only work on Chrome, also. Otherwise it'll just go to the top of the page.

**Comment by Khang5687** [comment]
Thanks for answering!
